// flow-typed signature: cd80a5e5ccb9c7f94b88a4c55fd6ac85
// flow-typed version: <<STUB>>/react-to-print_v2.12.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-to-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-to-print' {
  declare module.exports: any;
}
