// flow-typed signature: 20864a35b1bf1ef43423125a5e718897
// flow-typed version: <<STUB>>/react-dropzone_v11.3.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}
